// Mensagens da CLI em fonte única, por idioma de saída (userLanguage).
// `en` é o default (idioma canônico do pacote — ADR-0003); `pt-BR` preserva a
// experiência original. O núcleo não decide idioma: a borda resolve a precedência
// (flag > manifesto > locale) e passa a tabela pronta via getMessages().

const en = {
  unknownFlag: (flag) => `unknown flag: ${flag}`,
  unknownCommand: (command) => `unknown command: ${command}\n`,
  errorPrefix: (message) => `error: ${message}`,
  aborted: "aborted.",

  existingSkillsTitle: "Existing skills detected",
  invalidScope: (scope) => `invalid scope: ${scope}`,
  oldInstallWarn: (version) => `Old installation (v${version}, runtime-launcher model) detected — it will be MIGRATED to the new layout.`,
  resyncWarn: "Existing MGR installation detected — it will be re-synchronized.",
  planTitle: "Installation plan (self-contained per engine)",
  planProject: (projectId, scope) => `project:     ${projectId}    scope: ${scope}`,
  planEngines: (engines) => `engine(s):   ${engines}`,
  planStack: (language, architecture) => `language:    ${language}    architecture: ${architecture}`,
  planOutput: (lang) => `output:      ${lang}`,
  planOutputHint: "(skills output: conversation and artifacts)",
  planConfig: (dir) => `config   →   ${dir}`,
  planConfigHint: "(manifest.json + .env)",
  planSkillsDir: (dir) => `skills   →   ${dir}`,
  planSkills: (count, list) => `skills (${count}): ${list}`,
  dryRun: "(dry-run: nothing was written.)",
  confirmInstall: "Confirm installation?",
  installing: "Installing skills into the engines",
  installedAt: (dirs) => `Skills installed at ${dirs}.`,
  migrationInfo: (count) => `Migration: old model removed (${count} item(s), including .mgr-core).`,
  done: "Done! Start with /spec-init, then /spec-create per feature.",

  statusOldModel: "runtime-launcher (OLD — run `mgr update` to migrate)",
  statusProject: (id) => `  project: ${id}`,
  statusConfig: (dir) => `  config:  ${dir}`,
  statusStack: (language, architecture) => `  stack:   language=${language} architecture=${architecture}`,
  statusOutput: (lang) => `  output:  ${lang}`,
  statusSkillsDir: (dir) => `  skills:  ${dir}`,
  statusSkills: (list) => `  skills:  ${list}`,
  statusInstalledAt: (timestamp) => `  at:      ${timestamp}`,
  statusNone: "No MGR installation found (project or global).",

  updateMigrated: "(old installation migrated to the new layout)",
  updateDone: (scope, count, dirs) => `Re-synchronized (${scope}): ${count} skills at ${dirs}.`,

  uninstallConfirm: (scope) => `Remove the MGR installation (${scope})? docs/ and specs/ will be preserved.`,
  removedItem: (item) => `  removed: ${item}`,
  uninstalled: "Uninstalled.",

  buildDone: (dest, names) => `runtime built at ${dest}: ${names}`,

  bannerTagline: "AI Development Framework (SDD for coding agents)",
  bannerInstaller: (version) => `Installer v${version}`,
  bannerCreatedBy: (author, email) => `Created by ${author} · ${email}`,

  qEngines: "Which engines should receive the skills? (space marks, enter confirms)",
  qScope: "Installation scope?",
  scopeProjectHint: "in this repository",
  scopeGlobalHint: "for all projects (home)",
  qArchitecture: "Project architecture? (defines which arch-* skill to install)",
  qLanguage: "Main programming language? (defines specific helpers)",
  langOtherLabel: "other / unspecified",
  langOtherHint: "no language helpers",
  qOutputLanguage: "Output language? (conversation and artifacts generated by the skills)",
  outEnHint: "English",
  outPtHint: "Brazilian Portuguese",
  outOtherLabel: "other",
  outOtherHint: "specify which",
  qWhichLanguage: "Which language? (e.g. es-ES, fr-FR)",
  qOptionalEvidence: "Include the optional evidence-capture skill?",
  qProjectId: "MGR_PROJECT_ID (project identifier for the mgr-code memory)?",

  help: `MGR — Método Governado por Rastreabilidade (Traceability-Governed Method)

Usage: mgr <command> [options]

  install [repo]   installs the skills (selective) straight into the engine folder
                   (--engine claude-code|copilot|both, --scope, --language, --arch,
                    --user-language, --project-id, --all-skills, --skills-dir, --dry-run, -y)
  status [repo]    shows what is installed
  update [repo]    re-synchronizes (--scope)
  uninstall [repo] removes the installed skills (--scope, -y)
  build            generates a directory with the full content (--out)
  validate         validates the SKILL.md files
  list             lists the skills
  version          shows the version
`,
};

const ptBR = {
  unknownFlag: (flag) => `flag desconhecida: ${flag}`,
  unknownCommand: (command) => `comando desconhecido: ${command}\n`,
  errorPrefix: (message) => `erro: ${message}`,
  aborted: "abortado.",

  existingSkillsTitle: "Skills existentes detectadas",
  invalidScope: (scope) => `escopo inválido: ${scope}`,
  oldInstallWarn: (version) => `Instalação antiga (v${version}, modelo runtime-launcher) detectada — será MIGRADA para o novo layout.`,
  resyncWarn: "Instalação MGR existente detectada — será re-sincronizada.",
  planTitle: "Plano de instalação (autossuficiente por motor)",
  planProject: (projectId, scope) => `projeto:     ${projectId}    escopo: ${scope}`,
  planEngines: (engines) => `motor(es):   ${engines}`,
  planStack: (language, architecture) => `linguagem:   ${language}    arquitetura: ${architecture}`,
  planOutput: (lang) => `idioma:      ${lang}`,
  planOutputHint: "(saída das skills: conversa e artefatos)",
  planConfig: (dir) => `config   →   ${dir}`,
  planConfigHint: "(manifest.json + .env)",
  planSkillsDir: (dir) => `skills   →   ${dir}`,
  planSkills: (count, list) => `skills (${count}): ${list}`,
  dryRun: "(dry-run: nada foi escrito.)",
  confirmInstall: "Confirmar instalação?",
  installing: "Instalando skills nos motores",
  installedAt: (dirs) => `Skills instaladas em ${dirs}.`,
  migrationInfo: (count) => `Migração: modelo antigo removido (${count} item(ns), incluindo .mgr-core).`,
  done: "Pronto! Comece com /spec-init e depois /spec-create por feature.",

  statusOldModel: "runtime-launcher (ANTIGO — rode `mgr update` para migrar)",
  statusProject: (id) => `  projeto: ${id}`,
  statusConfig: (dir) => `  config:  ${dir}`,
  statusStack: (language, architecture) => `  stack:   linguagem=${language} arquitetura=${architecture}`,
  statusOutput: (lang) => `  idioma:  ${lang}`,
  statusSkillsDir: (dir) => `  skills:  ${dir}`,
  statusSkills: (list) => `  skills:  ${list}`,
  statusInstalledAt: (timestamp) => `  em:      ${timestamp}`,
  statusNone: "Nenhuma instalação MGR encontrada (projeto ou global).",

  updateMigrated: "(instalação antiga migrada para o novo layout)",
  updateDone: (scope, count, dirs) => `Re-sincronizado (${scope}): ${count} skills em ${dirs}.`,

  uninstallConfirm: (scope) => `Remover instalação MGR (${scope})? docs/ e specs/ serão preservados.`,
  removedItem: (item) => `  removido: ${item}`,
  uninstalled: "Desinstalado.",

  buildDone: (dest, names) => `runtime construído em ${dest}: ${names}`,

  bannerTagline: "AI Development Framework (SDD para agentes de código)",
  bannerInstaller: (version) => `Instalador v${version}`,
  bannerCreatedBy: (author, email) => `Criado por ${author} · ${email}`,

  qEngines: "Quais motores devem receber as skills? (espaço marca, enter confirma)",
  qScope: "Escopo da instalação?",
  scopeProjectHint: "neste repositório",
  scopeGlobalHint: "para todos os projetos (home)",
  qArchitecture: "Arquitetura do projeto? (define qual skill arch-* instalar)",
  qLanguage: "Linguagem principal? (define helpers específicos)",
  langOtherLabel: "outra / não especificar",
  langOtherHint: "sem helpers de linguagem",
  qOutputLanguage: "Idioma de saída? (conversa e artefatos gerados pelas skills)",
  outEnHint: "inglês",
  outPtHint: "português do Brasil",
  outOtherLabel: "outro",
  outOtherHint: "informar qual",
  qWhichLanguage: "Qual idioma? (ex.: es-ES, fr-FR)",
  qOptionalEvidence: "Incluir a skill opcional evidence-capture?",
  qProjectId: "MGR_PROJECT_ID (identificador do projeto para a memória do mgr-code)?",

  help: `MGR — Método Governado por Rastreabilidade

Uso: mgr <comando> [opções]

  install [repo]   instala as skills (seletivo) direto na pasta do motor
                   (--engine claude-code|copilot|both, --scope, --language, --arch,
                    --user-language, --project-id, --all-skills, --skills-dir, --dry-run, -y)
  status [repo]    mostra o que está instalado
  update [repo]    re-sincroniza (--scope)
  uninstall [repo] remove as skills instaladas (--scope, -y)
  build            gera um diretório com todo o conteúdo (--out)
  validate         valida as SKILL.md
  list             lista as skills
  version          mostra a versão
`,
};

// Seleciona a tabela pelo userLanguage: qualquer variante pt-* cai na pt-BR; o resto, en.
export function getMessages(lang) {
  return lang && String(lang).toLowerCase().startsWith("pt") ? ptBR : en;
}
