// Mensagens da CLI em fonte única, por idioma de saída (userLanguage).
// `en` é o default (idioma canônico do pacote — ADR-0003); `pt-BR` preserva a
// experiência original. O núcleo não decide idioma: a borda resolve a precedência
// (flag > manifesto > locale) e passa a tabela pronta via getMessages().

const en = {
  unknownFlag: (flag) => `unknown flag: ${flag}`,
  unknownCommand: (command) => `unknown command: ${command}\n`,
  errorPrefix: (message) => `error: ${message}`,
  aborted: "aborted.",

  existingSkillsTitle: "Existing skills detected",
  invalidScope: (scope) => `invalid scope: ${scope}`,
  oldInstallWarn: (version) => `Old installation (v${version}, runtime-launcher model) detected — it will be MIGRATED to the new layout.`,
  resyncWarn: "Existing MGR installation detected — it will be re-synchronized.",
  planTitle: "Installation plan (self-contained per engine)",
  planProject: (projectId, scope) => `project:     ${projectId}    scope: ${scope}`,
  planEngines: (engines) => `engine(s):   ${engines}`,
  planStack: (language, architecture) => `language:    ${language}    architecture: ${architecture}`,
  planOutput: (lang) => `output:      ${lang}`,
  planOutputHint: "(skills output: conversation and artifacts)",
  planConfig: (dir) => `config   →   ${dir}`,
  planConfigHint: "(manifest.json + .env)",
  planSkillsDir: (dir) => `skills   →   ${dir}`,
  planSkills: (count, list) => `skills (${count}): ${list}`,
  dryRun: "(dry-run: nothing was written.)",
  confirmInstall: "Confirm installation?",
  installing: "Installing skills into the engines",
  installedAt: (dirs) => `Skills installed at ${dirs}.`,
  migrationInfo: (count) => `Migration: old model removed (${count} item(s), including .mgr-core).`,
  done: "Done! Start with /spec-init, then /spec-create per feature.",

  statusOldModel: "runtime-launcher (OLD — run `mgr update` to migrate)",
  statusProject: (id) => `  project: ${id}`,
  statusConfig: (dir) => `  config:  ${dir}`,
  statusStack: (language, architecture) => `  stack:   language=${language} architecture=${architecture}`,
  statusOutput: (lang) => `  output:  ${lang}`,
  statusSkillsDir: (dir) => `  skills:  ${dir}`,
  statusSkills: (list) => `  skills:  ${list}`,
  statusInstalledAt: (timestamp) => `  at:      ${timestamp}`,
  statusNone: "No MGR installation found (project or global).",

  updateMigrated: "(old installation migrated to the new layout)",
  updateDone: (scope, count, dirs) => `Re-synchronized (${scope}): ${count} skills at ${dirs}.`,

  uninstallConfirm: (scope) => `Remove the MGR installation (${scope})? docs/ and specs/ will be preserved.`,
  removedItem: (item) => `  removed: ${item}`,
  uninstalled: "Uninstalled.",

  buildDone: (dest, names) => `runtime built at ${dest}: ${names}`,

  bannerTagline: "AI Development Framework (SDD for coding agents)",
  bannerInstaller: (version) => `Installer v${version}`,
  bannerCreatedBy: (author, email) => `Created by ${author} · ${email}`,

  qEngines: "Which engines should receive the skills? (space marks, enter confirms)",
  qScope: "Installation scope?",
  scopeProjectHint: "in this repository",
  scopeGlobalHint: "for all projects (home)",
  qArchitecture: "Project architecture? (defines which arch-* skill to install)",
  qLanguage: "Main programming language? (defines specific helpers)",
  langOtherLabel: "other / unspecified",
  langOtherHint: "no language helpers",
  qOutputLanguage: "Output language? (conversation and artifacts generated by the skills)",
  outEnHint: "English",
  outPtHint: "Brazilian Portuguese",
  outOtherLabel: "other",
  outOtherHint: "specify which",
  qWhichLanguage: "Which language? (e.g. es-ES, fr-FR)",
  qOptionalEvidence: "Include the optional evidence-capture skill?",
  qProjectId: "MGR_PROJECT_ID (project identifier for the mgr-code memory)?",

  pluginProposalTitle: "Plugin skill to install",
  pluginProposalName: (name, version) => `skill:       ${name}@${version}`,
  pluginProposalOrigin: (registry, url) => `origin:      ${registry} (${url})`,
  pluginProposalTrust: (trusted) => `trusted:     ${trusted ? "yes" : "no"}`,
  pluginProposalCategory: (category) => `category:    ${category}`,
  pluginProposalPermissions: (permissions) => `permissions: ${permissions}`,
  pluginProposalChecksum: (checksum) => `checksum:    ${checksum}`,
  pluginProposalEngines: (engines) => `engine(s):   ${engines}`,
  pluginProposalExtends: (base) => `extends:     ${base} (installed together; the extending skill takes precedence)`,
  pluginNoPermissions: "none declared",
  pluginConfirm: "Install this skill?",
  pluginNeedsTty: "`mgr add` requires an interactive terminal: every install is confirmed by a human and there is no bypass flag.",
  pluginInstalling: "Downloading and verifying",
  pluginInstalled: (name, dir) => `${name} installed at ${dir}.`,
  pluginWarning: (engine, warning) => `  warning (${engine}): ${warning}`,
  pluginLocked: (file) => `locked in ${file}.`,
  pluginCancelled: "installation cancelled by the user.",
  pluginRemoving: (name) => `Removing ${name} from the engines and the lockfile`,
  pluginCollisionQuestion: (methodSkill) => `The method already provides the skill "${methodSkill}" here. What should mgr do?`,
  pluginCollisionAlongside: "Install alongside",
  pluginCollisionAlongsideHint: (dir) => `plugin goes to ${dir}; the method skill stays`,
  pluginCollisionReplace: "Replace the method skill",
  pluginCollisionReplaceHint: (skill) => `plugin takes the ${skill} folder; recorded in the lockfile`,
  pluginRemoveReturns: (skill) => `  the method skill ${skill} comes back on the next \`mgr install\` or \`mgr update\``,
  statusPluginItemReplacing: (name, version, registry, skill) => `    ${name}@${version} (${registry}) — replaces the method skill ${skill}`,
  statusDivergenceTitle: "  divergences (lockfile vs disk):",
  statusDivergenceItem: (name) => `    ${name}: locked, but missing or different on disk`,
  statusDivergenceHint: "    run `mgr install` to restore the locked set",
  pluginRemoveSkipped: (dir, name) => `  kept ${dir}: it does not carry ${name}'s manifest, so another skill owns that folder`,
  pluginRemoved: (name) => `${name} removed.`,
  pluginUsageAdd: "usage: mgr add <@registry/skill>",
  pluginUsageRemove: "usage: mgr remove <@registry/skill>",

  registryAdding: (name) => `Adding registry "${name}" to .mgr-core/config.json`,
  registryAdded: (name, url) => `registry "${name}" added: ${url}`,
  registryRemoving: (name) => `Removing registry "${name}" from .mgr-core/config.json`,
  registryRemoved: (name) => `registry "${name}" removed.`,
  registryListTitle: "Configured registries",
  registryListItem: (name, url, trusted) => `  ${name}${trusted ? " (trusted)" : ""}  ${url}`,
  registryListEmpty: "No registry configured — run `mgr registry add <name> <index-url>`.",
  registryUsage: "usage: mgr registry add <name> <index-url> [--trusted] | mgr registry remove <name> | mgr registry list",

  pluginsInstalledTitle: "Installed plugin skills",
  pluginsInstalledItem: (name, version, registry, dir) => `  ${name}@${version}  (registry: ${registry}, folder: ${dir})`,
  pluginsAvailableTitle: "Available in the configured registries",
  pluginsAvailableItem: (name, version, category) => `  ${name}@${version}  [${category}]`,
  pluginsAvailableError: (registry, reason) => `  (registry "${registry}" unavailable: ${reason})`,
  statusPluginsTitle: (file) => `  plugins: ${file}`,
  statusPluginItem: (name, version, registry) => `    ${name}@${version} (${registry})`,

  restoring: (file) => `Restoring plugin skills from ${file}`,
  restoreDone: (count) => `${count} plugin skill(s) restored.`,
  restoreSkippedEngine: (name, engines) => `${name} is locked for ${engines}, not an active engine here; that copy was not restored`,

  help: `MGR — Método Governado por Rastreabilidade (Traceability-Governed Method)

Usage: mgr <command> [options]

  install [repo]   installs the skills (selective) straight into the engine folder
                   (--engine claude-code|copilot|both, --scope, --language, --arch,
                    --user-language, --project-id, --all-skills, --skills-dir, --dry-run, -y)
  status [repo]    shows what is installed
  update [repo]    re-synchronizes (--scope)
  uninstall [repo] removes the installed skills (--scope, -y)
  build            generates a directory with the full content (--out)
  validate         validates the SKILL.md files
  list             lists the skills
  version          shows the version

Plugin skills (https://github.com/maurigre/mgr-method/blob/main/docs/plugins.md):

  add <@registry/skill>       installs a plugin skill (always asks for confirmation)
  remove <@registry/skill>    removes a plugin skill
  registry add <name> <url> [--trusted] | remove <name> | list
                              manages the registries in .mgr-core/config.json
`,
};

const ptBR = {
  unknownFlag: (flag) => `flag desconhecida: ${flag}`,
  unknownCommand: (command) => `comando desconhecido: ${command}\n`,
  errorPrefix: (message) => `erro: ${message}`,
  aborted: "abortado.",

  existingSkillsTitle: "Skills existentes detectadas",
  invalidScope: (scope) => `escopo inválido: ${scope}`,
  oldInstallWarn: (version) => `Instalação antiga (v${version}, modelo runtime-launcher) detectada — será MIGRADA para o novo layout.`,
  resyncWarn: "Instalação MGR existente detectada — será re-sincronizada.",
  planTitle: "Plano de instalação (autossuficiente por motor)",
  planProject: (projectId, scope) => `projeto:     ${projectId}    escopo: ${scope}`,
  planEngines: (engines) => `motor(es):   ${engines}`,
  planStack: (language, architecture) => `linguagem:   ${language}    arquitetura: ${architecture}`,
  planOutput: (lang) => `idioma:      ${lang}`,
  planOutputHint: "(saída das skills: conversa e artefatos)",
  planConfig: (dir) => `config   →   ${dir}`,
  planConfigHint: "(manifest.json + .env)",
  planSkillsDir: (dir) => `skills   →   ${dir}`,
  planSkills: (count, list) => `skills (${count}): ${list}`,
  dryRun: "(dry-run: nada foi escrito.)",
  confirmInstall: "Confirmar instalação?",
  installing: "Instalando skills nos motores",
  installedAt: (dirs) => `Skills instaladas em ${dirs}.`,
  migrationInfo: (count) => `Migração: modelo antigo removido (${count} item(ns), incluindo .mgr-core).`,
  done: "Pronto! Comece com /spec-init e depois /spec-create por feature.",

  statusOldModel: "runtime-launcher (ANTIGO — rode `mgr update` para migrar)",
  statusProject: (id) => `  projeto: ${id}`,
  statusConfig: (dir) => `  config:  ${dir}`,
  statusStack: (language, architecture) => `  stack:   linguagem=${language} arquitetura=${architecture}`,
  statusOutput: (lang) => `  idioma:  ${lang}`,
  statusSkillsDir: (dir) => `  skills:  ${dir}`,
  statusSkills: (list) => `  skills:  ${list}`,
  statusInstalledAt: (timestamp) => `  em:      ${timestamp}`,
  statusNone: "Nenhuma instalação MGR encontrada (projeto ou global).",

  updateMigrated: "(instalação antiga migrada para o novo layout)",
  updateDone: (scope, count, dirs) => `Re-sincronizado (${scope}): ${count} skills em ${dirs}.`,

  uninstallConfirm: (scope) => `Remover instalação MGR (${scope})? docs/ e specs/ serão preservados.`,
  removedItem: (item) => `  removido: ${item}`,
  uninstalled: "Desinstalado.",

  buildDone: (dest, names) => `runtime construído em ${dest}: ${names}`,

  bannerTagline: "AI Development Framework (SDD para agentes de código)",
  bannerInstaller: (version) => `Instalador v${version}`,
  bannerCreatedBy: (author, email) => `Criado por ${author} · ${email}`,

  qEngines: "Quais motores devem receber as skills? (espaço marca, enter confirma)",
  qScope: "Escopo da instalação?",
  scopeProjectHint: "neste repositório",
  scopeGlobalHint: "para todos os projetos (home)",
  qArchitecture: "Arquitetura do projeto? (define qual skill arch-* instalar)",
  qLanguage: "Linguagem principal? (define helpers específicos)",
  langOtherLabel: "outra / não especificar",
  langOtherHint: "sem helpers de linguagem",
  qOutputLanguage: "Idioma de saída? (conversa e artefatos gerados pelas skills)",
  outEnHint: "inglês",
  outPtHint: "português do Brasil",
  outOtherLabel: "outro",
  outOtherHint: "informar qual",
  qWhichLanguage: "Qual idioma? (ex.: es-ES, fr-FR)",
  qOptionalEvidence: "Incluir a skill opcional evidence-capture?",
  qProjectId: "MGR_PROJECT_ID (identificador do projeto para a memória do mgr-code)?",

  pluginProposalTitle: "Skill plugável a instalar",
  pluginProposalName: (name, version) => `skill:       ${name}@${version}`,
  pluginProposalOrigin: (registry, url) => `origem:      ${registry} (${url})`,
  pluginProposalTrust: (trusted) => `confiável:   ${trusted ? "sim" : "não"}`,
  pluginProposalCategory: (category) => `categoria:   ${category}`,
  pluginProposalPermissions: (permissions) => `permissões:  ${permissions}`,
  pluginProposalChecksum: (checksum) => `checksum:    ${checksum}`,
  pluginProposalEngines: (engines) => `motor(es):   ${engines}`,
  pluginProposalExtends: (base) => `estende:     ${base} (instalada junto; a skill que estende tem precedência)`,
  pluginNoPermissions: "nenhuma declarada",
  pluginConfirm: "Instalar esta skill?",
  pluginNeedsTty: "`mgr add` exige terminal interativo: toda instalação é confirmada por uma pessoa e não há flag de bypass.",
  pluginInstalling: "Baixando e verificando",
  pluginInstalled: (name, dir) => `${name} instalada em ${dir}.`,
  pluginWarning: (engine, warning) => `  aviso (${engine}): ${warning}`,
  pluginLocked: (file) => `travada em ${file}.`,
  pluginCancelled: "instalação cancelada pelo usuário.",
  pluginRemoving: (name) => `Removendo ${name} dos motores e do lockfile`,
  pluginCollisionQuestion: (methodSkill) => `O método já fornece a skill "${methodSkill}" aqui. O que o mgr deve fazer?`,
  pluginCollisionAlongside: "Instalar ao lado",
  pluginCollisionAlongsideHint: (dir) => `o plugin vai para ${dir}; a skill do método fica`,
  pluginCollisionReplace: "Substituir a skill do método",
  pluginCollisionReplaceHint: (skill) => `o plugin ocupa a pasta ${skill}; fica registrado no lockfile`,
  pluginRemoveReturns: (skill) => `  a skill ${skill} do método volta no próximo \`mgr install\` ou \`mgr update\``,
  statusPluginItemReplacing: (name, version, registry, skill) => `    ${name}@${version} (${registry}) — substitui a skill ${skill} do método`,
  statusDivergenceTitle: "  divergências (lockfile x disco):",
  statusDivergenceItem: (name) => `    ${name}: travada no lockfile, ausente ou diferente no disco`,
  statusDivergenceHint: "    rode `mgr install` para restaurar o conjunto travado",
  pluginRemoveSkipped: (dir, name) => `  preservado ${dir}: não tem o manifest de ${name}, então a pasta é de outra skill`,
  pluginRemoved: (name) => `${name} removida.`,
  pluginUsageAdd: "uso: mgr add <@registry/skill>",
  pluginUsageRemove: "uso: mgr remove <@registry/skill>",

  registryAdding: (name) => `Adicionando o registry "${name}" ao .mgr-core/config.json`,
  registryAdded: (name, url) => `registry "${name}" adicionado: ${url}`,
  registryRemoving: (name) => `Removendo o registry "${name}" de .mgr-core/config.json`,
  registryRemoved: (name) => `registry "${name}" removido.`,
  registryListTitle: "Registries configurados",
  registryListItem: (name, url, trusted) => `  ${name}${trusted ? " (confiável)" : ""}  ${url}`,
  registryListEmpty: "Nenhum registry configurado — rode `mgr registry add <nome> <url-do-index>`.",
  registryUsage: "uso: mgr registry add <nome> <url-do-index> [--trusted] | mgr registry remove <nome> | mgr registry list",

  pluginsInstalledTitle: "Skills plugáveis instaladas",
  pluginsInstalledItem: (name, version, registry, dir) => `  ${name}@${version}  (registry: ${registry}, pasta: ${dir})`,
  pluginsAvailableTitle: "Disponíveis nos registries configurados",
  pluginsAvailableItem: (name, version, category) => `  ${name}@${version}  [${category}]`,
  pluginsAvailableError: (registry, reason) => `  (registry "${registry}" indisponível: ${reason})`,
  statusPluginsTitle: (file) => `  plugins: ${file}`,
  statusPluginItem: (name, version, registry) => `    ${name}@${version} (${registry})`,

  restoring: (file) => `Restaurando skills plugáveis de ${file}`,
  restoreDone: (count) => `${count} skill(s) plugável(is) restaurada(s).`,
  restoreSkippedEngine: (name, engines) => `${name} está travada para ${engines}, motor não ativo aqui; essa cópia não foi restaurada`,

  help: `MGR — Método Governado por Rastreabilidade

Uso: mgr <comando> [opções]

  install [repo]   instala as skills (seletivo) direto na pasta do motor
                   (--engine claude-code|copilot|both, --scope, --language, --arch,
                    --user-language, --project-id, --all-skills, --skills-dir, --dry-run, -y)
  status [repo]    mostra o que está instalado
  update [repo]    re-sincroniza (--scope)
  uninstall [repo] remove as skills instaladas (--scope, -y)
  build            gera um diretório com todo o conteúdo (--out)
  validate         valida as SKILL.md
  list             lista as skills
  version          mostra a versão

Skills plugáveis (ver https://github.com/maurigre/mgr-method/blob/main/docs/plugins.md):

  add <@registry/skill>       instala uma skill plugável (sempre pede confirmação)
  remove <@registry/skill>    remove uma skill plugável
  registry add <nome> <url> [--trusted] | remove <nome> | list
                              gerencia os registries em .mgr-core/config.json
`,
};

// Seleciona a tabela pelo userLanguage: qualquer variante pt-* cai na pt-BR; o resto, en.
export function getMessages(lang) {
  return lang && String(lang).toLowerCase().startsWith("pt") ? ptBR : en;
}
